### ISSUE TITLE
Remove window border?

### ISSUE THREAD

**Issue by Xe** [cznic/wm#1]
I'm trying to replicate irssi's interface with this library so I can make an IRC client. Is there a simple way to remove the window border from rendering?

**Comment by cznic** [comment]
Something like

```go
app.PostWait(func() {
        w.SetBorderTop(0)
        w.SetBorderLeft(0)
        w.SetBorderRight(0)
        w.SetBorderBottom(0)
})
```

should do the job. Please test and let me know if it works for you.

**Comment by Xe** [comment]
Yep. works.

**Comment by cznic** [comment]
@Xe Good luck with your project and please let me know if/when it get's published. I would be glad to include it on a "projects using wm" list in the README.
